### PR TITLE
Make sure that the sass gulp run happens *before* the minification

### PR DESCRIPTION
**Pull request by maniator**
Made the `css` task dependent on the `sass` task so that the tasks always run in the same order.

### CODE REVIEW

**Comment by jakegiltsoff** [comment]
@maniator ah nice thanks, I was having some troubles with that. I’ll test locally then get this merged.

**Comment by maniator** [comment]
Cool @jakegiltsoff  Let me know :-)

**Comment by maniator** [comment]
@jakegiltsoff any idea on when this can be merged? :-)

**Comment by elliottregan** [comment]
@jakegiltsoff Are you planning on continuing to support this project?

**Pull request merged**
